public CountryList()
        {
            Countries = new List<Country>();
            Countries.Add(new Country { Code = "AF", Description = "Afeganistão" });
            Countries.Add(new Country { Code = "ZA", Description = "Africa do Sul" });
            Countries.Add(new Country { Code = "AL", Description = "Albânia" });
            Countries.Add(new Country { Code = "GG", Description = "Alderney" });
            Countries.Add(new Country { Code = "DE", Description = "Alemanha" });
            Countries.Add(new Country { Code = "AD", Description = "Andorra" });
            Countries.Add(new Country { Code = "AO", Description = "Angola" });
            Countries.Add(new Country { Code = "AI", Description = "Anguila" });
            Countries.Add(new Country { Code = "AQ", Description = "Antártida" });
            Countries.Add(new Country { Code = "AG", Description = "Antigua e Barbuda" });
            Countries.Add(new Country { Code = "SX", Description = "Antilhas (Holandesas)" });
            Countries.Add(new Country { Code = "AP", Description = "Apátrida" });
            Countries.Add(new Country { Code = "SA", Description = "Arabia Saudita" });
            Countries.Add(new Country { Code = "DZ", Description = "Argelia" });
            Countries.Add(new Country { Code = "AR", Description = "Argentina" });
            Countries.Add(new Country { Code = "AM", Description = "Armenia" });
            Countries.Add(new Country { Code = "AW", Description = "Aruba" });
            Countries.Add(new Country { Code = "AU", Description = "Austrália" });
            Countries.Add(new Country { Code = "AT", Description = "Áustria" });
            Countries.Add(new Country { Code = "AZ", Description = "Azerbaijan" });
            Countries.Add(new Country { Code = "BS", Description = "Bahamas" });
            Countries.Add(new Country { Code = "BH", Description = "Bahrain" });
            Countries.Add(new Country { Code = "BD", Description = "Bangladesh" });
            Countries.Add(new Country { Code = "BB", Description = "Barbados" });
            Countries.Add(new Country { Code = "BE", Description = "Belgium" });
            Countries.Add(new Country { Code = "BZ", Description = "Belize" });
            Countries.Add(new Country { Code = "BJ", Description = "Benin" });
            Countries.Add(new Country { Code = "BM", Description = "Bermudas" });
            Countries.Add(new Country { Code = "BY", Description = "Bielorussia" });
            Countries.Add(new Country { Code = "MM", Description = "Birmania" });
            Countries.Add(new Country { Code = "BO", Description = "Bolívia" });
            Countries.Add(new Country { Code = "BQ", Description = "Bonaire, Santo Eustáquio e Saba" });
            Countries.Add(new Country { Code = "BA", Description = "Bosnia Herzegovina" });
            Countries.Add(new Country { Code = "BW", Description = "Botswana" });
            Countries.Add(new Country { Code = "BR", Description = "Brasil" });
            Countries.Add(new Country { Code = "BN", Description = "Brunei Darussalam" });
            Countries.Add(new Country { Code = "BG", Description = "Bulgária" });
            Countries.Add(new Country { Code = "BF", Description = "Burkina Faso" });
            Countries.Add(new Country { Code = "BI", Description = "Burundi" });
            Countries.Add(new Country { Code = "BT", Description = "Butão" });
            Countries.Add(new Country { Code = "CV", Description = "Cabo Verde" });
            Countries.Add(new Country { Code = "CM", Description = "Camarões" });
            Countries.Add(new Country { Code = "KH", Description = "Camboja" });
            Countries.Add(new Country { Code = "CA", Description = "Canada" });
            Countries.Add(new Country { Code = "KZ", Description = "Cazaquistão" });
            Countries.Add(new Country { Code = "TD", Description = "Chade" });
            Countries.Add(new Country { Code = "CL", Description = "Chile" });
            Countries.Add(new Country { Code = "CY", Description = "Chipre" });
            Countries.Add(new Country { Code = "CO", Description = "Colombia" });
            Countries.Add(new Country { Code = "KM", Description = "Comoras" });
            Countries.Add(new Country { Code = "CG", Description = "Congo" });
            Countries.Add(new Country { Code = "KP", Description = "Coreia do Norte" });
            Countries.Add(new Country { Code = "KR", Description = "Coreia do Sul" });
            Countries.Add(new Country { Code = "CI", Description = "Costa do Marfim" });
            Countries.Add(new Country { Code = "CR", Description = "Costa Rica" });
            Countries.Add(new Country { Code = "HR", Description = "Croacia" });
            Countries.Add(new Country { Code = "CU", Description = "Cuba" });
            Countries.Add(new Country { Code = "CW", Description = "Curaçau" });
            Countries.Add(new Country { Code = "DK", Description = "Dinamarca" });
            Countries.Add(new Country { Code = "DM", Description = "Dominica" });
            Countries.Add(new Country { Code = "EG", Description = "Egipto" });
            Countries.Add(new Country { Code = "SV", Description = "El Salvador" });
            Countries.Add(new Country { Code = "AE", Description = "Emiratos Arabes Unidos" });
            Countries.Add(new Country { Code = "EC", Description = "Equador" });
            Countries.Add(new Country { Code = "ER", Description = "Eritreia" });
            Countries.Add(new Country { Code = "SK", Description = "Eslovaquia" });
            Countries.Add(new Country { Code = "SI", Description = "Eslovenia" });
            Countries.Add(new Country { Code = "ES", Description = "Espanha" });
            Countries.Add(new Country { Code = "US", Description = "Estados Unidos" });
            Countries.Add(new Country { Code = "EE", Description = "Estónia" });
            Countries.Add(new Country { Code = "ET", Description = "Etiopia" });
            Countries.Add(new Country { Code = "FO", Description = "Faroe Islands" });
            Countries.Add(new Country { Code = "KN", Description = "Federação de São Cristovão e Neves" });
            Countries.Add(new Country { Code = "FJ", Description = "Fiji" });
            Countries.Add(new Country { Code = "PH", Description = "Filipinas" });
            Countries.Add(new Country { Code = "FI", Description = "Finlandia" });
            Countries.Add(new Country { Code = "FR", Description = "France" });
            Countries.Add(new Country { Code = "GA", Description = "Gabon" });
            Countries.Add(new Country { Code = "GM", Description = "Gambia" });
            Countries.Add(new Country { Code = "GE", Description = "Geórgia" });
            Countries.Add(new Country { Code = "GS", Description = "Geórgia do Sul e Ilhas Sandwich" });
            Countries.Add(new Country { Code = "GI", Description = "Gibraltar" });
            Countries.Add(new Country { Code = "GD", Description = "Granada" });
            Countries.Add(new Country { Code = "GR", Description = "Grecia" });
            Countries.Add(new Country { Code = "GL", Description = "Gronelandia" });
            Countries.Add(new Country { Code = "GP", Description = "Guadalupe" });
            Countries.Add(new Country { Code = "GU", Description = "Guam" });
            Countries.Add(new Country { Code = "GT", Description = "Guatemala" });
            Countries.Add(new Country { Code = "GG", Description = "Guernsey" });
            Countries.Add(new Country { Code = "GY", Description = "Guiana" });
            Countries.Add(new Country { Code = "GF", Description = "Guiana Francesa" });
            Countries.Add(new Country { Code = "GN", Description = "Guiné" });
            Countries.Add(new Country { Code = "GQ", Description = "Guiné Equatorial" });
            Countries.Add(new Country { Code = "GW", Description = "Guiné-Bissau" });
            Countries.Add(new Country { Code = "HT", Description = "Haiti" });
            Countries.Add(new Country { Code = "HN", Description = "Honduras" });
            Countries.Add(new Country { Code = "HK", Description = "Hong-Kong" });
            Countries.Add(new Country { Code = "HU", Description = "Hungria" });
            Countries.Add(new Country { Code = "BV", Description = "Ilha Bouvet" });
            Countries.Add(new Country { Code = "CX", Description = "Ilha Christmas" });
            Countries.Add(new Country { Code = "HM", Description = "Ilha Heard e Ilhas Mcdonald" });
            Countries.Add(new Country { Code = "NF", Description = "Ilha Norfolk" });
            Countries.Add(new Country { Code = "AX", Description = "Ilhas Aland" });
            Countries.Add(new Country { Code = "KY", Description = "Ilhas Caimão" });
            Countries.Add(new Country { Code = "CC", Description = "Ilhas Cocos (Keeling)" });
            Countries.Add(new Country { Code = "CK", Description = "Ilhas Cook" });
            Countries.Add(new Country { Code = "FK", Description = "Ilhas Falkland (Malvinas)" });
            Countries.Add(new Country { Code = "MP", Description = "Ilhas Marianas do Norte" });
            Countries.Add(new Country { Code = "MH", Description = "Ilhas Marshall" });
            Countries.Add(new Country { Code = "MU", Description = "Ilhas Mauricias" });
            Countries.Add(new Country { Code = "UM", Description = "Ilhas Menores Distantes dos Estados Unidos" });
            Countries.Add(new Country { Code = "SB", Description = "Ilhas Salomão" });
            Countries.Add(new Country { Code = "TC", Description = "Ilhas Turcas e Caicos" });
            Countries.Add(new Country { Code = "VG", Description = "Ilhas Virgens (Britânicas)" });
            Countries.Add(new Country { Code = "IN", Description = "India" });
            Countries.Add(new Country { Code = "ID", Description = "Indonesia" });
            Countries.Add(new Country { Code = "IR", Description = "Irão" });
            Countries.Add(new Country { Code = "IQ", Description = "Iraque" });
            Countries.Add(new Country { Code = "IE", Description = "Irlanda" });
            Countries.Add(new Country { Code = "IS", Description = "Islandia" });
            Countries.Add(new Country { Code = "IM", Description = "Isle of Man" });
            Countries.Add(new Country { Code = "IL", Description = "Israel" });
            Countries.Add(new Country { Code = "IT", Description = "Italia" });
            Countries.Add(new Country { Code = "JM", Description = "Jamaica" });
            Countries.Add(new Country { Code = "JP", Description = "Japão" });
            Countries.Add(new Country { Code = "JE", Description = "Jersey" });
            Countries.Add(new Country { Code = "JO", Description = "Jordania" });
            Countries.Add(new Country { Code = "XK", Description = "Kosovo" });
            Countries.Add(new Country { Code = "KW", Description = "Kuwait" });
            Countries.Add(new Country { Code = "LS", Description = "Lesoto" });
            Countries.Add(new Country { Code = "LV", Description = "Letonia" });
            Countries.Add(new Country { Code = "LB", Description = "Líbano" });
            Countries.Add(new Country { Code = "LR", Description = "Libéria" });
            Countries.Add(new Country { Code = "LY", Description = "Libia" });
            Countries.Add(new Country { Code = "LI", Description = "Liechtenstein" });
            Countries.Add(new Country { Code = "LT", Description = "Lituania" });
            Countries.Add(new Country { Code = "LU", Description = "Luxemburgo" });
            Countries.Add(new Country { Code = "MO", Description = "Macau" });
            Countries.Add(new Country { Code = "MK", Description = "Macedonia" });
            Countries.Add(new Country { Code = "MG", Description = "Madagáscar" });
            Countries.Add(new Country { Code = "MY", Description = "Malásia" });
            Countries.Add(new Country { Code = "MW", Description = "Malaui" });
            Countries.Add(new Country { Code = "MV", Description = "Maldivas" });
            Countries.Add(new Country { Code = "ML", Description = "Mali" });
            Countries.Add(new Country { Code = "MT", Description = "Malta" });
            Countries.Add(new Country { Code = "MA", Description = "Marrocos" });
            Countries.Add(new Country { Code = "MQ", Description = "Martinica" });
            Countries.Add(new Country { Code = "MR", Description = "Mauritania" });
            Countries.Add(new Country { Code = "YT", Description = "Mayotte" });
            Countries.Add(new Country { Code = "MX", Description = "México" });
            Countries.Add(new Country { Code = "FM", Description = "Micronésia" });
            Countries.Add(new Country { Code = "MZ", Description = "Moçambique" });
            Countries.Add(new Country { Code = "MD", Description = "Moldavia" });
            Countries.Add(new Country { Code = "MC", Description = "Mónaco" });
            Countries.Add(new Country { Code = "MN", Description = "Mongólia" });
            Countries.Add(new Country { Code = "MS", Description = "Monserrate" });
            Countries.Add(new Country { Code = "ME", Description = "Montenegro" });
            Countries.Add(new Country { Code = "NA", Description = "Namibia" });
            Countries.Add(new Country { Code = "NR", Description = "Nauru" });
            Countries.Add(new Country { Code = "NP", Description = "Nepal" });
            Countries.Add(new Country { Code = "NI", Description = "Nicaragua" });
            Countries.Add(new Country { Code = "NE", Description = "Niger" });
            Countries.Add(new Country { Code = "NG", Description = "Nigéria" });
            Countries.Add(new Country { Code = "NU", Description = "Niue" });
            Countries.Add(new Country { Code = "NO", Description = "Noruega" });
            Countries.Add(new Country { Code = "NC", Description = "Nova Caledónia" });
            Countries.Add(new Country { Code = "NZ", Description = "Nova Zelandia" });
            Countries.Add(new Country { Code = "OM", Description = "Oman" });
            Countries.Add(new Country { Code = "NL", Description = "Paises Baixos" });
            Countries.Add(new Country { Code = "PS", Description = "Palestina" });
            Countries.Add(new Country { Code = "PA", Description = "Panamá" });
            Countries.Add(new Country { Code = "PG", Description = "Papua Nova Guiné" });
            Countries.Add(new Country { Code = "PK", Description = "Paquistão" });
            Countries.Add(new Country { Code = "PY", Description = "Paraguai" });
            Countries.Add(new Country { Code = "PE", Description = "Peru" });
            Countries.Add(new Country { Code = "PN", Description = "Pitcairn" });
            Countries.Add(new Country { Code = "PF", Description = "Polinésia Francesa" });
            Countries.Add(new Country { Code = "PL", Description = "Polónia" });
            Countries.Add(new Country { Code = "PT", Description = "Portugal" });
            Countries.Add(new Country { Code = "PR", Description = "Puerto Rico" });
            Countries.Add(new Country { Code = "QA", Description = "Qatar" });
            Countries.Add(new Country { Code = "KG", Description = "Quirguistão" });
            Countries.Add(new Country { Code = "GB", Description = "Reino Unido" });
            Countries.Add(new Country { Code = "EH", Description = "República Árabe Saharaui Democrática" });
            Countries.Add(new Country { Code = "CF", Description = "Republica Centro-Africana" });
            Countries.Add(new Country { Code = "CZ", Description = "Republica Checa" });
            Countries.Add(new Country { Code = "CD", Description = "Republica Democrática do Congo" });
            Countries.Add(new Country { Code = "DJ", Description = "República do Djibouti" });
            Countries.Add(new Country { Code = "GH", Description = "Republica do Gana" });
            Countries.Add(new Country { Code = "KI", Description = "República do Kiribati" });
            Countries.Add(new Country { Code = "LA", Description = "Republica do Laos" });
            Countries.Add(new Country { Code = "PW", Description = "Republica do Palau" });
            Countries.Add(new Country { Code = "KE", Description = "Republica do Quenia" });
            Countries.Add(new Country { Code = "DO", Description = "Republica Dominicana" });
            Countries.Add(new Country { Code = "CN", Description = "Republica Popular da China" });
            Countries.Add(new Country { Code = "RE", Description = "Reunião" });
            Countries.Add(new Country { Code = "RO", Description = "Roménia" });
            Countries.Add(new Country { Code = "RW", Description = "Ruanda" });
            Countries.Add(new Country { Code = "RU", Description = "Russia" });
            Countries.Add(new Country { Code = "WS", Description = "Samoa" });
            Countries.Add(new Country { Code = "AS", Description = "Samoa Americana" });
            Countries.Add(new Country { Code = "SH", Description = "Santa Helena, Ascensão e Tristão da Cunha" });
            Countries.Add(new Country { Code = "LC", Description = "Santa Luzia" });
            Countries.Add(new Country { Code = "BL", Description = "São Bartolomeu" });
            Countries.Add(new Country { Code = "SM", Description = "São Marino" });
            Countries.Add(new Country { Code = "MF", Description = "São Martinho (parte francesa)" });
            Countries.Add(new Country { Code = "PM", Description = "São Pedro e Miquelon" });
            Countries.Add(new Country { Code = "ST", Description = "São Tomé e Principe" });
            Countries.Add(new Country { Code = "VC", Description = "São Vicente e Grenadinas" });
            Countries.Add(new Country { Code = "SN", Description = "Senegal" });
            Countries.Add(new Country { Code = "RS", Description = "Serbia" });
            Countries.Add(new Country { Code = "SL", Description = "Serra Leoa" });
            Countries.Add(new Country { Code = "SC", Description = "Seychelles" });
            Countries.Add(new Country { Code = "SG", Description = "Singapura" });
            Countries.Add(new Country { Code = "SY", Description = "Siria" });
            Countries.Add(new Country { Code = "SO", Description = "Somália" });
            Countries.Add(new Country { Code = "LK", Description = "Sri Lanka" });
            Countries.Add(new Country { Code = "SZ", Description = "Suazilandia" });
            Countries.Add(new Country { Code = "SD", Description = "Sudão" });
            Countries.Add(new Country { Code = "SS", Description = "Sudão do Sul" });
            Countries.Add(new Country { Code = "SE", Description = "Suécia" });
            Countries.Add(new Country { Code = "CH", Description = "Suiça" });
            Countries.Add(new Country { Code = "SR", Description = "Suriname" });
            Countries.Add(new Country { Code = "SJ", Description = "Svalbard e a Ilha de Jan Mayen" });
            Countries.Add(new Country { Code = "TH", Description = "Tailandia" });
            Countries.Add(new Country { Code = "TW", Description = "Taiwan" });
            Countries.Add(new Country { Code = "TJ", Description = "Tajiquistão" });
            Countries.Add(new Country { Code = "TZ", Description = "Tanzania" });
            Countries.Add(new Country { Code = "IO", Description = "Território Britânico do Oceano Índico" });
            Countries.Add(new Country { Code = "TF", Description = "Territórios Franceses do Sul" });
            Countries.Add(new Country { Code = "TL", Description = "Timor Oriental" });
            Countries.Add(new Country { Code = "TG", Description = "Togo" });
            Countries.Add(new Country { Code = "TK", Description = "Tokelau" });
            Countries.Add(new Country { Code = "TO", Description = "Tonga" });
            Countries.Add(new Country { Code = "TT", Description = "Trinidade e Tobago" });
            Countries.Add(new Country { Code = "TN", Description = "Tunisia" });
            Countries.Add(new Country { Code = "TM", Description = "Turquemenistão" });
            Countries.Add(new Country { Code = "TR", Description = "Turquia" });
            Countries.Add(new Country { Code = "TV", Description = "Tuvalu" });
            Countries.Add(new Country { Code = "UA", Description = "Ucrania" });
            Countries.Add(new Country { Code = "UG", Description = "Uganda" });
            Countries.Add(new Country { Code = "UY", Description = "Uruguai" });
            Countries.Add(new Country { Code = "UZ", Description = "Uzebequistão" });
            Countries.Add(new Country { Code = "VU", Description = "Vanuatu" });
            Countries.Add(new Country { Code = "VA", Description = "Vaticano" });
            Countries.Add(new Country { Code = "VE", Description = "Venezuela" });
            Countries.Add(new Country { Code = "VN", Description = "Vietname" });
            Countries.Add(new Country { Code = "VI", Description = "Virgin Islands" });
            Countries.Add(new Country { Code = "WF", Description = "Wallis e Futuna (Ilhas)" });
            Countries.Add(new Country { Code = "YE", Description = "Yemen" });
            Countries.Add(new Country { Code = "ZM", Description = "Zambia" });
            Countries.Add(new Country { Code = "ZM", Description = "Zâmbia" });
            Countries.Add(new Country { Code = "TZ", Description = "Zanzibar" });
            Countries.Add(new Country { Code = "ZW", Description = "Zimbabwe" });
        }
